{% set version = '0.10' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pca3d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pca3d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pca3d/pca3d_{{ version }}.tar.gz
  sha256: c3e95f50a4d1bdc6b48ad18bc496131bd1601ec2502e5f20684ec0239726f5ae

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - r-base
    - r-ellipse
    - r-rgl
  run:
    - r-base
    - r-ellipse
    - r-rgl

test:
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64 $R -e "library('pca3d')"           # [not win]
    - "\"%R%\" -e \"library('pca3d')\""  # [win]

about:
  home: https://logfc.wordpress.com
  license: GPL-2
  summary: Functions simplifying presentation of PCA models in a 3D interactive representation
    using 'rgl'.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo

# Package: pca3d
# Type: Package
# Title: Three Dimensional PCA Plots
# Version: 0.10
# Date: 2017-02-17
# Author: January Weiner
# URL: http://logfc.wordpress.com
# Maintainer: January Weiner <january.weiner@gmail.com>
# Description: Functions simplifying presentation of PCA models in a 3D interactive representation using 'rgl'.
# License: GPL-2
# Imports: rgl,ellipse
# Suggests: knitr
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2017-02-17 08:37:19.609 UTC; january
# Repository: CRAN
# Date/Publication: 2017-02-17 14:38:20
