{% set version = "0.10.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pca3d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pca3d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pca3d/pca3d_{{ version }}.tar.gz
  sha256: a6cbc3d57cdf89ac9cb6b7ce48ab8cd9a929b092425ee35c3fd8c0f6d1b1f476

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - r-base
    - r-ellipse
    - r-rgl
  run:
    - r-base
    - r-ellipse
    - r-rgl

test:
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64: ${BUILD_PREFIX}/lib $R -e "library('pca3d')"  # [not win]
    - "\"%R%\" -e \"library('pca3d')\""  # [win]

about:
  home: https://logfc.wordpress.com
  license: GPL-2.0-only
  summary: Functions simplifying presentation of PCA models in a 3D interactive representation using 'rgl'.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
