{% set version = '0.10' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pca3d
  version: {{ version|replace("-", "_") }}

source:
  fn: pca3d_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pca3d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pca3d/pca3d_{{ version }}.tar.gz
  sha256: c3e95f50a4d1bdc6b48ad18bc496131bd1601ec2502e5f20684ec0239726f5ae

build:
  number: 1
  skip: true  # [win32 or osx]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ellipse
    - r-rgl

  run:
    - r-base
    - r-ellipse
    - r-rgl

test:
  commands:
    - $R -e "library('pca3d')"           # [not win]
    - "\"%R%\" -e \"library('pca3d')\""  # [win]

about:
  home: https://logfc.wordpress.com/
  license: GPL-2
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]
  summary: Functions simplifying presentation of PCA models in a 3D interactive representation
    using 'rgl'.

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - nsoranzo
