travis:
  secure:
    BINSTAR_TOKEN: UcRQxtFEwsQ3oQTe9lrrN951Y7vY1zGEA+Kfp40JJN9d9CFuYiph/djPx/0sVVzOkZnpl3jEcOboMftHobYw1kUlaywvBso0EC6ysWRmuybrqMVhS/CB5pL862nsB0116Dgur4oI/UDYD6vkT7D/rDPbEJLZIcydQ+gHq1OlHGiVlKsC0Bxj62ATVAd7nWC15AqcSkh5M8XxD743OTq4+3Kuw3ABKOS+Ecs2APxfpHNqcTgBuuudEMw3o/PVXqSwdIDBnzADe2G/Lz12T0yWG/8Kgy/iAHHpUbuPZS8UKToSn3uG23css2ijrBnAslY5pYGUthUfcYceEyG92jH7QmRIIZDoZZikVQLzsIJ9D100HYmjls1ySsaWHct102h46aL1lN/uDxUWPI51TVNUnFviJozfg+fPUMXSGigPGbMI849KmzpGX4v25Jd8vjE5w9YYmyXMRqiIFTcPqnLhvMv67B9qtk8fuej0pgWSlPr6I2Hlk/KVHrfLgn/JmB3KyGCswHl5tLLbXamWxBcelnLhHyxh7j2OqAGh1zmu0hrMKgvFE8gGAZXBwsrknt0UsFOtrKvttCNJKFP0ik9t33tFl50p4T0xDsN39JGkL0LAvzAz7fBWM5g0qZYdo3xmGxtDIUNNDxJ9fBwE8wU/3frAYogX+YC/lTIjXqtqeMs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
