travis:
  secure:
    BINSTAR_TOKEN: wkQRIlzVfaQRFqLCFjiSmQeIX8gN7CCD23pW66jdcrcvQT8KX9IhnXXcr3yKGBMPZpnz7+VSz5qmM8OW13vc1suZMzkfBDgI/CyAxo5BgH4O20hBJNX2SfT8QBGE3jESmDRyZ6fRZlHWiZwuLNNfnm9IP3YFSQzhF3X7MAfdrxzz5eI70gdqAo+zSHEiKTEJgifHd1oJ6uzq69JuGzOPaiKtuv/Q0w0zCXs3zPDoBVAn1jI1Bv1bJDB6roD7RDyU9diCivFW+3EdhcRfeUXQ15Rdfv0BiQ6Y36DZy0RHNvozNefpPgcOMAnCkchuwnif4qzPwOULnL8nNctcN2X6DTFLrDvTwmaMMgARc0J/Dp3VFy66JvUdUWYk6i3Z9YVwIIrnbICROT195Vd1SoR0GS/A0ab9oUv3LYrjLh4z9UmeRDLuRRQF7ULLs5XZbHK3w/2XaZdkxzDoCLwu5y23MsX5b2Tv6etUCBG8plAsVI3/CGMY08nbCROw3srtSuunpNLcFHija85ZCTXR6h9ix5JOAfQwIGPTigtm9Fuw2KiTHaG4aoM5MWAxnl6F2N7T27VPbU/cMog5WJWxiOiIlhWxLRkaSTk/+ZIqa360wZt5gdjvGzDdtDoDq7vhkCDf+1FGAN54jDpPyVHN1UKaRsZo9zMHmMNnxImc57Idvys=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
